-- TRIGGERS E SEQUENCE
-- BENEFICIARIOS
CREATE SEQUENCE SEQ_BENEFICIARIOS_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_BENEFICIARIOS
BEFORE INSERT ON BENEFICIARIOS
FOR EACH ROW
BEGIN
    :NEW.ben_id := SEQ_BENEFICIARIOS_ID.NEXTVAL;
END;
/

-- BOLSAS
CREATE SEQUENCE SEQ_BOLSAS_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_BOLSAS
BEFORE INSERT ON BOLSAS
FOR EACH ROW
BEGIN
    :NEW.bol_id := SEQ_BOLSAS_ID.NEXTVAL;
END;
/

-- CURSOS
CREATE SEQUENCE SEQ_CURSOS_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_CURSOS
BEFORE INSERT ON CURSOS
FOR EACH ROW
BEGIN
    :NEW.crs_id := SEQ_CURSOS_ID.NEXTVAL;
END;
/



-- ESTADOS
CREATE SEQUENCE SEQ_ESTADOS_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_ESTADOS
BEFORE INSERT ON ESTADOS
FOR EACH ROW
BEGIN
    :NEW.est_id := SEQ_ESTADOS_ID.NEXTVAL;
END;
/

-- INSTITUICOES

CREATE SEQUENCE SEQ_INSTITUICOES_ID START WITH 1335 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_INSTITUICOES
BEFORE INSERT ON INSTITUICOES
FOR EACH ROW
BEGIN
    :NEW.ies_id := SEQ_INSTITUICOES_ID.NEXTVAL;
END;
/

-- LOCALIZACOES
CREATE SEQUENCE SEQ_LOCALIZACOES_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_LOCALIZACOES
BEFORE INSERT ON LOCALIZACOES
FOR EACH ROW
BEGIN
    :NEW.loc_id := SEQ_LOCALIZACOES_ID.NEXTVAL;
END;
/

-- MATRICULAS
CREATE SEQUENCE SEQ_MATRICULAS_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_MATRICULAS
BEFORE INSERT ON MATRICULAS
FOR EACH ROW
BEGIN
    :NEW.mat_id := SEQ_MATRICULAS_ID.NEXTVAL;
END;
/

-- MODALIDADES
CREATE SEQUENCE SEQ_MODALIDADES_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_MODALIDADES
BEFORE INSERT ON MODALIDADES
FOR EACH ROW
BEGIN
    :NEW.mod_id := SEQ_MODALIDADES_ID.NEXTVAL;
END;
/

-- RACAS
CREATE SEQUENCE SEQ_RACAS_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_RACAS
BEFORE INSERT ON RACAS
FOR EACH ROW
BEGIN
    :NEW.rac_id := SEQ_RACAS_ID.NEXTVAL;
END;
/

-- REGIAO
CREATE SEQUENCE SEQ_REGIAO_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_REGIAO
BEFORE INSERT ON REGIAO
FOR EACH ROW
BEGIN
    :NEW.reg_id := SEQ_REGIAO_ID.NEXTVAL;
END;
/

-- SEXOS
CREATE SEQUENCE SEQ_SEXOS_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_SEXOS
BEFORE INSERT ON SEXOS
FOR EACH ROW
BEGIN
    :NEW.sex_id := SEQ_SEXOS_ID.NEXTVAL;
END;
/

-- TIPO
CREATE SEQUENCE SEQ_TIPO_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_TIPO
BEFORE INSERT ON TIPO
FOR EACH ROW
BEGIN
    :NEW.tip_id := SEQ_TIPO_ID.NEXTVAL;
END;
/

-- TURNOS
CREATE SEQUENCE SEQ_TURNOS_ID START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SEQ_TURNOS
BEFORE INSERT ON TURNOS
FOR EACH ROW
BEGIN
    :NEW.tur_id := SEQ_TURNOS_ID.NEXTVAL;
END;
/